Dziennik/Dziennik/Models/Wykładowca.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Dziennik.Models
{
    public class Wykładowca
    {
        public int ID { get; set; }
        [Required]
        [RegularExpression(@"^[A-ZŻŹŃĄŚŁĘÓ]+[a-zA-ZŻŹŃĄŚŁĘÓżźćńąśłęó''-'\s]*$", ErrorMessage = "Zacznij z dużej litery i używaj wyłącznie liter")]
        [StringLength(15, ErrorMessage = "Imię nie może być dłuższe niż 15 znaków.")]
        public string Imię { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "Nazwisko nie może być dłuższe niż 20 znaków.")]
        [RegularExpression(@"^[A-ZŻŹŃĄŚŁĘÓ]+[a-zA-ZŻŹŃĄŚŁĘÓżźćńąśłęó''-'\s]*$", ErrorMessage = "Zacznij z dużej litery i używaj wyłącznie liter")]
        public string Nazwisko { get; set; }

        public virtual ICollection<Przedmiot> Przedmioty { get; set; }
    }
}

Dziennik/Dziennik/Controllers/PrzedmiotController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dziennik.Models;
using Dziennik.DAL;

namespace Dziennik.Controllers
{
    public class PrzedmiotController : Controller
    {
        private DziennikContext db = new DziennikContext();

        // GET: /Przedmiot/
        public ActionResult Index()
        {
            var przedmioty = db.Przedmioty.Include(p => p.Wykładowca);
            return View(przedmioty.ToList());
        }

        // GET: /Przedmiot/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmiot przedmiot = db.Przedmioty.Find(id);
            if (przedmiot == null)
            {
                return HttpNotFound();
            }
            return View(przedmiot);
        }

        // GET: /Przedmiot/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.WykładowcaID = new SelectList(db.Wykładowcy, "ID", "Nazwisko");
            return View();
        }

        // POST: /Przedmiot/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,WykładowcaID,Nazwa,Skrót,PunktyECTS")] Przedmiot przedmiot)
        {
            if (ModelState.IsValid)
            {
                db.Przedmioty.Add(przedmiot);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.WykładowcaID = new SelectList(db.Wykładowcy, "ID", "Nazwisko", przedmiot.WykładowcaID);
            return View(przedmiot);
        }

        // GET: /Przedmiot/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmiot przedmiot = db.Przedmioty.Find(id);
            if (przedmiot == null)
            {
                return HttpNotFound();
            }
            ViewBag.WykładowcaID = new SelectList(db.Wykładowcy, "ID", "Nazwisko", przedmiot.WykładowcaID);
            return View(przedmiot);
        }

        // POST: /Przedmiot/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,WykładowcaID,Nazwa,Skrót,PunktyECTS")] Przedmiot przedmiot)
        {
            if (ModelState.IsValid)
            {
                db.Entry(przedmiot).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.WykładowcaID = new SelectList(db.Wykładowcy, "ID", "Nazwisko", przedmiot.WykładowcaID);
            return View(przedmiot);
        }

        // GET: /Przedmiot/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmiot przedmiot = db.Przedmioty.Find(id);
            if (przedmiot == null)
            {
                return HttpNotFound();
            }
            return View(przedmiot);
        }

        // POST: /Przedmiot/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Przedmiot przedmiot = db.Przedmioty.Find(id);
            db.Przedmioty.Remove(przedmiot);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dziennik/Dziennik/Controllers/WykładowcaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dziennik.Models;
using Dziennik.DAL;

namespace Dziennik.Controllers
{
    public class WykładowcaController : Controller
    {
        private DziennikContext db = new DziennikContext();

        // GET: /Wykładowca/
        public ActionResult Index()
        {
            return View(db.Wykładowcy.ToList());
        }

        // GET: /Wykładowca/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wykładowca wykładowca = db.Wykładowcy.Find(id);
            if (wykładowca == null)
            {
                return HttpNotFound();
            }
            return View(wykładowca);
        }

        // GET: /Wykładowca/Create
        [Authorize(Roles="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Wykładowca/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Imię,Nazwisko")] Wykładowca wykładowca)
        {
            if (ModelState.IsValid)
            {
                db.Wykładowcy.Add(wykładowca);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(wykładowca);
        }

        // GET: /Wykładowca/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wykładowca wykładowca = db.Wykładowcy.Find(id);
            if (wykładowca == null)
            {
                return HttpNotFound();
            }
            return View(wykładowca);
        }

        // POST: /Wykładowca/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Imię,Nazwisko")] Wykładowca wykładowca)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wykładowca).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(wykładowca);
        }

        // GET: /Wykładowca/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wykładowca wykładowca = db.Wykładowcy.Find(id);
            if (wykładowca == null)
            {
                return HttpNotFound();
            }
            return View(wykładowca);
        }

        // POST: /Wykładowca/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Wykładowca wykładowca = db.Wykładowcy.Find(id);
            db.Wykładowcy.Remove(wykładowca);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dziennik/Dziennik/Views/Wykładowca/Create.cshtml
@model Dziennik.Models.Wykładowca

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj wykładowcę</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Imię, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imię)
                @Html.ValidationMessageFor(model => model.Imię)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwisko, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwisko)
                @Html.ValidationMessageFor(model => model.Nazwisko)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Dziennik/Dziennik/Views/Wykładowca/Delete.cshtml
@model Dziennik.Models.Wykładowca

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń wykładowcę</h2>

<h3>Czy jesteś pewny że chcesz usunąć tego wykładowcę?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Imię)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imię)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-danger" /> |
            @Html.ActionLink("Powrót", "Index")
        </div>
    }
</div>

Dziennik/Dziennik/Views/Wykładowca/Details.cshtml
@model Dziennik.Models.Wykładowca

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły wykładowcy</h2>

<div>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Imię)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imię)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Przedmioty)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Nazwa</th>
                    <th>Skrót</th>
                    <th>Punkty ECTS</th>
                </tr>
                @foreach (var item in Model.Przedmioty)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nazwa)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Skrót)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PunktyECTS)
                        </td>
                    </tr>
                }
                <th>
                    @Html.ActionLink("Dodaj przedmiot", "Create", "Przedmiot")
                </th>
            </table>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Powrót", "Index")
</p>

Dziennik/Dziennik/Views/Wykładowca/Edit.cshtml
@model Dziennik.Models.Wykładowca

@{
    ViewBag.Title = "Edit";
}

<h2>Edytuj wykładowcę</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Imię, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imię)
                @Html.ValidationMessageFor(model => model.Imię)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwisko, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwisko)
                @Html.ValidationMessageFor(model => model.Nazwisko)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Dziennik/Dziennik/Views/Wykładowca/Index.cshtml
@model IEnumerable<Dziennik.Models.Wykładowca>

@{
    ViewBag.Title = "Index";
}

<h2>Lista wykładowców</h2>

<p>
    @Html.ActionLink("Dodaj wykładowcę", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Imię)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Imię)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nazwisko)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Szczegóły", "Details", new { id=item.ID }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>