Dziennik/Dziennik/Models/Przedmiot.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Dziennik.Models
{
    public class Przedmiot
    {
        public int ID { get; set; }
        public int WykładowcaID { get; set; }
        [StringLength(80, ErrorMessage = "Nazwa nie może być dłuższa niż 35 znaków.")]
        [Required]
        [Display(Name="Nazwa przedmiotu")]
        public string Nazwa { get; set; }
        [StringLength(8, ErrorMessage = "Skrót nie może być dłuższy niż 8 znaków.")]
        [Required]
        public string Skrót { get; set; }
        [Display(Name="Punkty ECTS")]
        public int PunktyECTS { get; set; }

        public virtual ICollection<Wynik> Wyniki { get; set; }
        [Required]
        public virtual Wykładowca Wykładowca { get; set; }
    }
}

Dziennik/Dziennik/Controllers/PrzedmiotController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dziennik.Models;
using Dziennik.DAL;

namespace Dziennik.Controllers
{
    public class PrzedmiotController : Controller
    {
        private DziennikContext db = new DziennikContext();

        // GET: /Przedmiot/
        public ActionResult Index()
        {
            var przedmioty = db.Przedmioty.Include(p => p.Wykładowca);
            return View(przedmioty.ToList());
        }

        // GET: /Przedmiot/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmiot przedmiot = db.Przedmioty.Find(id);
            if (przedmiot == null)
            {
                return HttpNotFound();
            }
            return View(przedmiot);
        }

        // GET: /Przedmiot/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.WykładowcaID = new SelectList(db.Wykładowcy, "ID", "Nazwisko");
            return View();
        }

        // POST: /Przedmiot/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,WykładowcaID,Nazwa,Skrót,PunktyECTS")] Przedmiot przedmiot)
        {
            if (ModelState.IsValid)
            {
                db.Przedmioty.Add(przedmiot);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.WykładowcaID = new SelectList(db.Wykładowcy, "ID", "Nazwisko", przedmiot.WykładowcaID);
            return View(przedmiot);
        }

        // GET: /Przedmiot/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmiot przedmiot = db.Przedmioty.Find(id);
            if (przedmiot == null)
            {
                return HttpNotFound();
            }
            ViewBag.WykładowcaID = new SelectList(db.Wykładowcy, "ID", "Nazwisko", przedmiot.WykładowcaID);
            return View(przedmiot);
        }

        // POST: /Przedmiot/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,WykładowcaID,Nazwa,Skrót,PunktyECTS")] Przedmiot przedmiot)
        {
            if (ModelState.IsValid)
            {
                db.Entry(przedmiot).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.WykładowcaID = new SelectList(db.Wykładowcy, "ID", "Nazwisko", przedmiot.WykładowcaID);
            return View(przedmiot);
        }

        // GET: /Przedmiot/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmiot przedmiot = db.Przedmioty.Find(id);
            if (przedmiot == null)
            {
                return HttpNotFound();
            }
            return View(przedmiot);
        }

        // POST: /Przedmiot/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Przedmiot przedmiot = db.Przedmioty.Find(id);
            db.Przedmioty.Remove(przedmiot);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dziennik/Dziennik/Controllers/WynikController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dziennik.Models;
using Dziennik.DAL;

namespace Dziennik.Controllers
{
    public class WynikController : Controller
    {
        private DziennikContext db = new DziennikContext();

        // GET: /Wynik/
        public ActionResult Index()
        {
            var wyniki = db.Wyniki.Include(w => w.Przedmiot).Include(w => w.Student);
            return View(wyniki.ToList());
        }

        // GET: /Wynik/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wynik wynik = db.Wyniki.Find(id);
            if (wynik == null)
            {
                return HttpNotFound();
            }
            return View(wynik);
        }

        // GET: /Wynik/Create
        [Authorize(Roles = "Admin, Wykładowca")]
        public ActionResult Create()
        {
            ViewBag.PrzedmiotID = new SelectList(db.Przedmioty, "ID", "Nazwa");
            ViewBag.StudentID = new SelectList(db.Studenci, "ID", "NrAlbumu");
            return View();
        }

        // POST: /Wynik/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,StudentID,PrzedmiotID,Ocena")] Wynik wynik)
        {
            //try
            //{
                if (ModelState.IsValid)
                {
                    db.Wyniki.Add(wynik);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                //}
                //catch (DataException /* dex */)
                //{
                //    //Log the error (uncomment dex variable name and add a line here to write a log.
                //    ModelState.AddModelError("", "Nie można zapisać danych. Spróbuj ponownie, jeżeli problem wystąpi ponownie skontaktuj się z administratorem.");
                //}

            ViewBag.PrzedmiotID = new SelectList(db.Przedmioty, "ID", "Nazwa", wynik.PrzedmiotID);
            ViewBag.StudentID = new SelectList(db.Studenci, "ID", "NrAlbumu", wynik.StudentID);
            return View(wynik);
        }

        // GET: /Wynik/Edit/5
        [Authorize(Roles = "Admin, Wykładowca")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wynik wynik = db.Wyniki.Find(id);
            if (wynik == null)
            {
                return HttpNotFound();
            }
            ViewBag.PrzedmiotID = new SelectList(db.Przedmioty, "ID", "Nazwa", wynik.PrzedmiotID);
            ViewBag.StudentID = new SelectList(db.Studenci, "ID", "NrAlbumu", wynik.StudentID);
            return View(wynik);
        }

        // POST: /Wynik/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,StudentID,PrzedmiotID,Ocena")] Wynik wynik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wynik).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PrzedmiotID = new SelectList(db.Przedmioty, "ID", "Nazwa", wynik.PrzedmiotID);
            ViewBag.StudentID = new SelectList(db.Studenci, "ID", "NrAlbumu", wynik.StudentID);
            return View(wynik);
        }

        // GET: /Wynik/Delete/5
        [Authorize(Roles = "Admin, Wykładowca")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wynik wynik = db.Wyniki.Find(id);
            if (wynik == null)
            {
                return HttpNotFound();
            }
            return View(wynik);
        }

        // POST: /Wynik/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Wynik wynik = db.Wyniki.Find(id);
            db.Wyniki.Remove(wynik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dziennik/Dziennik/Views/Przedmiot/Create.cshtml
@model Dziennik.Models.Przedmiot

@{
    ViewBag.Title = "Dodaj przedmiot";
}

<h2>Dodaj przedmiot</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.WykładowcaID, "Prowadzący", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WykładowcaID", String.Empty)
                @Html.ValidationMessageFor(model => model.Wykładowca.Nazwisko)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa)
                @Html.ValidationMessageFor(model => model.Nazwa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Skrót, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Skrót)
                @Html.ValidationMessageFor(model => model.Skrót)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PunktyECTS, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PunktyECTS)
                @Html.ValidationMessageFor(model => model.PunktyECTS)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Dziennik/Dziennik/Views/Przedmiot/Delete.cshtml
@model Dziennik.Models.Przedmiot

@{
    ViewBag.Title = "Usuń";
}

<h2>Usuń przedmiot</h2>

<h3>Czy jesteś pewny że chcesz usunąć ten przedmiot?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Wykładowca.Imię)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wykładowca.Imię)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Skrót)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Skrót)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PunktyECTS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PunktyECTS)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-danger" /> |
            @Html.ActionLink("Powrót", "Index")
        </div>
    }
</div>

Dziennik/Dziennik/Views/Przedmiot/Details.cshtml
@model Dziennik.Models.Przedmiot

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły przedmiotu</h2>

<div>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            Prowadzący
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wykładowca.Imię)
            @Html.DisplayFor(model => model.Wykładowca.Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Skrót)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Skrót)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PunktyECTS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PunktyECTS)
        </dd>
        @if (Context.User.IsInRole("Admin") || Context.User.IsInRole("Wykładowca")) { 
        <dt>
            Oceny
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Nr albumu</th>
                    <th>Imię studenta</th>
                    <th>Nazwisko studenta</th>
                    <th>Ocena</th>
                </tr>
                @foreach (var item in Model.Wyniki)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Student.NrAlbumu)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Student.Imię)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Student.Nazwisko)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ocena)
                        </td>
                    </tr>
                }
                <th>
                    @Html.ActionLink("Dodaj ocenę", "Create", "Wynik")
                </th>
            </table>
        </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Powrót", "Index")
</p>

Dziennik/Dziennik/Views/Przedmiot/Edit.cshtml
@model Dziennik.Models.Przedmiot

@{
    ViewBag.Title = "Edit";
}

<h2>Edytuj przedmiot</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.WykładowcaID, "Prowadzący", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WykładowcaID", String.Empty)
                @Html.ValidationMessageFor(model => model.Wykładowca.Nazwisko)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa)
                @Html.ValidationMessageFor(model => model.Nazwa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Skrót, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Skrót)
                @Html.ValidationMessageFor(model => model.Skrót)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PunktyECTS, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PunktyECTS)
                @Html.ValidationMessageFor(model => model.PunktyECTS)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Dziennik/Dziennik/Views/Przedmiot/Index.cshtml
@model IEnumerable<Dziennik.Models.Przedmiot>

@{
    ViewBag.Title = "Index";
}

<h2>Lista przedmiotów</h2>

<p>
    @Html.ActionLink("Dodaj przedmiot", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Nazwa przedmiotu
        </th>
        <th>
            Prowadzący
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Skrót)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PunktyECTS)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Wykładowca.Imię)
            @Html.DisplayFor(modelItem => item.Wykładowca.Nazwisko)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Skrót)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PunktyECTS)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Szczegóły", "Details", new { id=item.ID }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>